version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciamento-pedidos
      MYSQL_USERNAME: root

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: openjdk:17
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8090"
    depends_on:
      - mysql
    networks:
      - springboot-mysql
    volumes:
      - app-data:/app/uploads

volumes:
  mysql-data:
  app-data:

networks:
  springboot-mysql:
    driver: bridge